### ISSUE TITLE
Save a picture on disk

### ISSUE THREAD

**Issue by Ceecker51** [Ceecker51/JPEG-Encoder#12]
Save a picture object on disk (Format: *.ppm)

**Comment by mrvary** [comment]
Ich hab noch mal drüber nachgedacht, Voraussetzung hierfür wäre, dass es eine Funktion gibt, die aus einem YCbCr Bild ein RGB Bild macht, das kann dann vernünftig gespeichert werden. Da .ppm von RGB ausgeht würde es nur verfälschte Ergebnisse liefern, die YCbCr Werte zu speichern. Außerdem könnten wir drüber nachdenken statt double wieder auf int zu gehen (ganz am Ende im .jpg stehen ja auch nur int Werte)
